// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 3d_printer

#include "../ui.h"

lv_obj_t *ui_Screen_1_Print1 = NULL;lv_obj_t *ui_Background3 = NULL;lv_obj_t *ui_Panel_Header3 = NULL;lv_obj_t *ui_Label_Header3 = NULL;lv_obj_t *ui_Label_Header6 = NULL;lv_obj_t *ui_BTN_Menu_Print_S4 = NULL;lv_obj_t *ui_BTN_Menu_Setting_S4 = NULL;lv_obj_t *ui_S1_Content_Panel3 = NULL;lv_obj_t *ui_Display_Heat_S2 = NULL;lv_obj_t *ui_DT6 = NULL;lv_obj_t *ui_Label_Printing_Head_Temp1 = NULL;lv_obj_t *ui_IMG_Head2 = NULL;lv_obj_t *ui_Label_Head_Temp2 = NULL;lv_obj_t *ui_Panel5 = NULL;lv_obj_t *ui_DT3_copy1 = NULL;lv_obj_t *ui_Label_Printing_Bed_Temp2 = NULL;lv_obj_t *ui_IMG_Head3 = NULL;lv_obj_t *ui_Label_Bed_Temp2 = NULL;lv_obj_t *ui_Label_Printing_Bed_Temp3 = NULL;lv_obj_t *ui_Label_Printing_Head_Temp3 = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Panel_Buttons_S2 = NULL;lv_obj_t *ui_BTN_Pause1 = NULL;lv_obj_t *ui_BTN_Pause_Top1 = NULL;lv_obj_t *ui_Image_Pause1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label1 = NULL;
// event funtions
void ui_event_BTN_Menu_Setting_S4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen_2_Move1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_2_Move1_screen_init);
}
}

// build funtions

void ui_Screen_1_Print1_screen_init(void)
{
ui_Screen_1_Print1 = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_Screen_1_Print1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_1_Print1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Background3 = lv_img_create(ui_Screen_1_Print1);
lv_img_set_src(ui_Background3, &ui_img_new_bg_png);
lv_obj_set_width( ui_Background3, 800);
lv_obj_set_height( ui_Background3, 480);
lv_obj_set_align( ui_Background3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Background3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_Panel_Header3 = lv_obj_create(ui_Screen_1_Print1);
lv_obj_set_width( ui_Panel_Header3, 665);
lv_obj_set_height( ui_Panel_Header3, 39);
lv_obj_set_x( ui_Panel_Header3, -30 );
lv_obj_set_y( ui_Panel_Header3, 0 );
lv_obj_set_align( ui_Panel_Header3, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Panel_Header3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_Header3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_Header3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Panel_Header3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Panel_Header3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_Header3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Header3 = lv_label_create(ui_Panel_Header3);
lv_obj_set_width( ui_Label_Header3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Header3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Header3, -78 );
lv_obj_set_y( ui_Label_Header3, -3 );
lv_obj_set_align( ui_Label_Header3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Header3,"THU-NPWT");
lv_label_set_recolor(ui_Label_Header3,"true");
lv_obj_set_style_text_color(ui_Label_Header3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Header3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Header3, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Header6 = lv_label_create(ui_Panel_Header3);
lv_obj_set_width( ui_Label_Header6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Header6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Header6, 58 );
lv_obj_set_y( ui_Label_Header6, -3 );
lv_obj_set_align( ui_Label_Header6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Header6,"负压伤口治疗装置");
lv_label_set_recolor(ui_Label_Header6,"true");
lv_obj_set_style_text_color(ui_Label_Header6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Header6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Header6, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Menu_Print_S4 = lv_img_create(ui_Screen_1_Print1);
lv_img_set_src(ui_BTN_Menu_Print_S4, &ui_img_new_home_png);
lv_obj_set_width( ui_BTN_Menu_Print_S4, 79);
lv_obj_set_height( ui_BTN_Menu_Print_S4, 240);
lv_obj_add_flag( ui_BTN_Menu_Print_S4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Print_S4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Menu_Setting_S4 = lv_img_create(ui_Screen_1_Print1);
lv_img_set_src(ui_BTN_Menu_Setting_S4, &ui_img_btn_setting_png);
lv_obj_set_width( ui_BTN_Menu_Setting_S4, 79);
lv_obj_set_height( ui_BTN_Menu_Setting_S4, 240);
lv_obj_set_align( ui_BTN_Menu_Setting_S4, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_BTN_Menu_Setting_S4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Setting_S4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BTN_Menu_Setting_S4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_S1_Content_Panel3 = lv_obj_create(ui_Screen_1_Print1);
lv_obj_set_width( ui_S1_Content_Panel3, 720);
lv_obj_set_height( ui_S1_Content_Panel3, 411);
lv_obj_set_x( ui_S1_Content_Panel3, -4 );
lv_obj_set_y( ui_S1_Content_Panel3, -24 );
lv_obj_set_align( ui_S1_Content_Panel3, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_S1_Content_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_S1_Content_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_S1_Content_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_S1_Content_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_S1_Content_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_S1_Content_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_S1_Content_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_S1_Content_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Display_Heat_S2 = lv_obj_create(ui_S1_Content_Panel3);
lv_obj_set_width( ui_Display_Heat_S2, 384);
lv_obj_set_height( ui_Display_Heat_S2, 134);
lv_obj_set_x( ui_Display_Heat_S2, -254 );
lv_obj_set_y( ui_Display_Heat_S2, 243 );
lv_obj_set_align( ui_Display_Heat_S2, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Display_Heat_S2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Display_Heat_S2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Display_Heat_S2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Display_Heat_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Display_Heat_S2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Display_Heat_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Display_Heat_S2, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Display_Heat_S2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Display_Heat_S2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Display_Heat_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Display_Heat_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Display_Heat_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Display_Heat_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Display_Heat_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DT6 = lv_obj_create(ui_Display_Heat_S2);
lv_obj_set_width( ui_DT6, lv_pct(50));
lv_obj_set_height( ui_DT6, lv_pct(100));
lv_obj_set_align( ui_DT6, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_DT6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DT6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DT6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_DT6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_DT6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DT6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DT6, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DT6, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DT6, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DT6, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Printing_Head_Temp1 = lv_label_create(ui_DT6);
lv_obj_set_width( ui_Label_Printing_Head_Temp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Printing_Head_Temp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Printing_Head_Temp1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Printing_Head_Temp1,"设定负压");
lv_label_set_recolor(ui_Label_Printing_Head_Temp1,"true");
lv_obj_set_style_text_color(ui_Label_Printing_Head_Temp1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Printing_Head_Temp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Printing_Head_Temp1, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IMG_Head2 = lv_img_create(ui_DT6);
lv_img_set_src(ui_IMG_Head2, &ui_img_icn_head_png);
lv_obj_set_width( ui_IMG_Head2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_IMG_Head2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_IMG_Head2, 7 );
lv_obj_set_y( ui_IMG_Head2, -6 );
lv_obj_set_align( ui_IMG_Head2, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_IMG_Head2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_Label_Head_Temp2 = lv_label_create(ui_DT6);
lv_obj_set_width( ui_Label_Head_Temp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Head_Temp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Head_Temp2, 11 );
lv_obj_set_y( ui_Label_Head_Temp2, -11 );
lv_obj_set_align( ui_Label_Head_Temp2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Head_Temp2,"-120mmHg");
lv_obj_set_style_text_color(ui_Label_Head_Temp2, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Head_Temp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Head_Temp2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Display_Heat_S2);
lv_obj_set_width( ui_Panel5, 2);
lv_obj_set_height( ui_Panel5, 47);
lv_obj_set_x( ui_Panel5, 0 );
lv_obj_set_y( ui_Panel5, -9 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DT3_copy1 = lv_obj_create(ui_Display_Heat_S2);
lv_obj_set_width( ui_DT3_copy1, lv_pct(50));
lv_obj_set_height( ui_DT3_copy1, lv_pct(100));
lv_obj_set_align( ui_DT3_copy1, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_DT3_copy1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DT3_copy1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DT3_copy1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_DT3_copy1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_DT3_copy1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DT3_copy1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DT3_copy1, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DT3_copy1, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DT3_copy1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DT3_copy1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Printing_Bed_Temp2 = lv_label_create(ui_DT3_copy1);
lv_obj_set_width( ui_Label_Printing_Bed_Temp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Printing_Bed_Temp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Printing_Bed_Temp2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Printing_Bed_Temp2,"工作模式");
lv_label_set_recolor(ui_Label_Printing_Bed_Temp2,"true");
lv_obj_set_style_text_color(ui_Label_Printing_Bed_Temp2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Printing_Bed_Temp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Printing_Bed_Temp2, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_IMG_Head3 = lv_img_create(ui_DT3_copy1);
lv_img_set_src(ui_IMG_Head3, &ui_img_icn_bed_png);
lv_obj_set_width( ui_IMG_Head3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_IMG_Head3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_IMG_Head3, 11 );
lv_obj_set_y( ui_IMG_Head3, -8 );
lv_obj_set_align( ui_IMG_Head3, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_IMG_Head3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_Label_Bed_Temp2 = lv_label_create(ui_DT3_copy1);
lv_obj_set_width( ui_Label_Bed_Temp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Bed_Temp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Bed_Temp2, 11 );
lv_obj_set_y( ui_Label_Bed_Temp2, -9 );
lv_obj_set_align( ui_Label_Bed_Temp2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Bed_Temp2,"持续模式");
lv_obj_set_style_text_color(ui_Label_Bed_Temp2, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Bed_Temp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Bed_Temp2, &ui_font_chinese24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Printing_Bed_Temp3 = lv_label_create(ui_DT3_copy1);
lv_obj_set_width( ui_Label_Printing_Bed_Temp3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Printing_Bed_Temp3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Printing_Bed_Temp3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Printing_Bed_Temp3,"工作模式");
lv_label_set_recolor(ui_Label_Printing_Bed_Temp3,"true");
lv_obj_set_style_text_color(ui_Label_Printing_Bed_Temp3, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Printing_Bed_Temp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Printing_Bed_Temp3, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Printing_Head_Temp3 = lv_label_create(ui_Display_Heat_S2);
lv_obj_set_width( ui_Label_Printing_Head_Temp3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Printing_Head_Temp3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Printing_Head_Temp3, -134 );
lv_obj_set_y( ui_Label_Printing_Head_Temp3, 91 );
lv_obj_set_align( ui_Label_Printing_Head_Temp3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Printing_Head_Temp3,"密封性");
lv_label_set_recolor(ui_Label_Printing_Head_Temp3,"true");
lv_obj_set_style_text_color(ui_Label_Printing_Head_Temp3, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Printing_Head_Temp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Printing_Head_Temp3, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_Display_Heat_S2);
lv_bar_set_value(ui_Bar1,90,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 245);
lv_obj_set_height( ui_Bar1, 25);
lv_obj_set_x( ui_Bar1, 37 );
lv_obj_set_y( ui_Bar1, 35 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );

lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x055A6F), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Bar1, lv_color_hex(0x6CF8F5), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Bar1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Bar1, 200, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Bar1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Panel_Buttons_S2 = lv_obj_create(ui_S1_Content_Panel3);
lv_obj_set_width( ui_Panel_Buttons_S2, 202);
lv_obj_set_height( ui_Panel_Buttons_S2, 200);
lv_obj_set_x( ui_Panel_Buttons_S2, -37 );
lv_obj_set_y( ui_Panel_Buttons_S2, -26 );
lv_obj_set_align( ui_Panel_Buttons_S2, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_Panel_Buttons_S2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_Buttons_S2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_Buttons_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Panel_Buttons_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Panel_Buttons_S2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_Buttons_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel_Buttons_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel_Buttons_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel_Buttons_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel_Buttons_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Pause1 = lv_img_create(ui_Panel_Buttons_S2);
lv_img_set_src(ui_BTN_Pause1, &ui_img_btn_print_down_png);
lv_obj_set_width( ui_BTN_Pause1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Pause1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_BTN_Pause1, 21 );
lv_obj_set_y( ui_BTN_Pause1, 21 );
lv_obj_set_align( ui_BTN_Pause1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_BTN_Pause1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_BTN_Pause_Top1 = lv_img_create(ui_BTN_Pause1);
lv_img_set_src(ui_BTN_Pause_Top1, &ui_img_btn_print_top_off_png);
lv_obj_set_width( ui_BTN_Pause_Top1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Pause_Top1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Pause_Top1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Pause_Top1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_set_style_radius(ui_BTN_Pause_Top1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_BTN_Pause_Top1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_BTN_Pause_Top1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_Pause_Top1, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_shadow_opa(ui_BTN_Pause_Top1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_width(ui_BTN_Pause_Top1, 9, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_spread(ui_BTN_Pause_Top1, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_ofs_x(ui_BTN_Pause_Top1, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_ofs_y(ui_BTN_Pause_Top1, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_color(ui_BTN_Pause_Top1, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_BTN_Pause_Top1, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_BTN_Pause_Top1, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_BTN_Pause_Top1, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_x(ui_BTN_Pause_Top1, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_y(ui_BTN_Pause_Top1, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_BTN_Pause_Top1, lv_color_hex(0x67799B), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_BTN_Pause_Top1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Image_Pause1 = lv_img_create(ui_BTN_Pause_Top1);
lv_img_set_src(ui_Image_Pause1, &ui_img_open_png);
lv_obj_set_width( ui_Image_Pause1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image_Pause1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Image_Pause1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Pause1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_img_set_zoom(ui_Image_Pause1,240);
lv_obj_set_style_img_recolor(ui_Image_Pause1, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image_Pause1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen_1_Print1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 207 );
lv_obj_set_y( ui_Label2, -59 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"mmHg");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen_1_Print1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -326 );
lv_obj_set_y( ui_Label1, -76 );
lv_obj_set_align( ui_Label1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label1,"-110");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_big_font, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BTN_Menu_Setting_S4, ui_event_BTN_Menu_Setting_S4, LV_EVENT_ALL, NULL);

}

void ui_Screen_1_Print1_screen_destroy(void)
{
   if (ui_Screen_1_Print1) lv_obj_del(ui_Screen_1_Print1);

// NULL screen variables
ui_Screen_1_Print1= NULL;
ui_Background3= NULL;
ui_Panel_Header3= NULL;
ui_Label_Header3= NULL;
ui_Label_Header6= NULL;
ui_BTN_Menu_Print_S4= NULL;
ui_BTN_Menu_Setting_S4= NULL;
ui_S1_Content_Panel3= NULL;
ui_Display_Heat_S2= NULL;
ui_DT6= NULL;
ui_Label_Printing_Head_Temp1= NULL;
ui_IMG_Head2= NULL;
ui_Label_Head_Temp2= NULL;
ui_Panel5= NULL;
ui_DT3_copy1= NULL;
ui_Label_Printing_Bed_Temp2= NULL;
ui_IMG_Head3= NULL;
ui_Label_Bed_Temp2= NULL;
ui_Label_Printing_Bed_Temp3= NULL;
ui_Label_Printing_Head_Temp3= NULL;
ui_Bar1= NULL;
ui_Panel_Buttons_S2= NULL;
ui_BTN_Pause1= NULL;
ui_BTN_Pause_Top1= NULL;
ui_Image_Pause1= NULL;
ui_Label2= NULL;
ui_Label1= NULL;

}
