// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 3d_printer

#ifndef UI_SCREEN_2_MOVE1_H
#define UI_SCREEN_2_MOVE1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_2_Move1
extern void ui_Screen_2_Move1_screen_init(void);
extern void ui_Screen_2_Move1_screen_destroy(void);
extern lv_obj_t *ui_Screen_2_Move1;
extern lv_obj_t *ui_Background4;
extern lv_obj_t *ui_Panel_Header4;
extern lv_obj_t *ui_Label_Header5;
extern lv_obj_t *ui_Label_Header7;
extern void ui_event_BTN_Menu_Print_S5( lv_event_t * e);
extern lv_obj_t *ui_BTN_Menu_Print_S5;
extern lv_obj_t *ui_S1_Content_Panel4;
extern lv_obj_t *ui_Display_Pos_y1;
extern lv_obj_t *ui_DP6;
extern lv_obj_t *ui_Label_Z_Position1;
extern lv_obj_t *ui_Label_Z_Position_Number1;
extern lv_obj_t *ui_BTN_Move_Z1;
extern void ui_event_GLOW_7( lv_event_t * e);
extern lv_obj_t *ui_GLOW_7;
extern void ui_event_GLOW_8( lv_event_t * e);
extern lv_obj_t *ui_GLOW_8;
extern lv_obj_t *ui_BTN_Image_Top1;
extern lv_obj_t *ui_Label_Z_Position_1;
extern lv_obj_t *ui_Arrow_Z_up1;
extern lv_obj_t *ui_Arrow_Z_Down1;
extern lv_obj_t *ui_BTN_Reset1;
extern lv_obj_t *ui_Label_Reset3;
extern lv_obj_t *ui_Roller_Number3;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Roller7;
extern lv_obj_t *ui_Label_Steps3;
extern lv_obj_t *ui_BTN_Move_Z2;
extern void ui_event_GLOW_9( lv_event_t * e);
extern lv_obj_t *ui_GLOW_9;
extern void ui_event_GLOW_10( lv_event_t * e);
extern lv_obj_t *ui_GLOW_10;
extern lv_obj_t *ui_BTN_Image_Top2;
extern lv_obj_t *ui_Label_Z_Position_3;
extern lv_obj_t *ui_Arrow_Z_up2;
extern lv_obj_t *ui_Arrow_Z_Down2;
extern lv_obj_t *ui_BTN_Move_Z3;
extern void ui_event_GLOW_11( lv_event_t * e);
extern lv_obj_t *ui_GLOW_11;
extern void ui_event_GLOW_12( lv_event_t * e);
extern lv_obj_t *ui_GLOW_12;
extern lv_obj_t *ui_BTN_Image_Top3;
extern lv_obj_t *ui_Label_Z_Position_4;
extern lv_obj_t *ui_Arrow_Z_up3;
extern lv_obj_t *ui_Arrow_Z_Down3;
extern lv_obj_t *ui_BTN_Reset2;
extern lv_obj_t *ui_Label_Reset1;
extern lv_obj_t *ui_Display_Pos_XY2;
extern lv_obj_t *ui_DP7;
extern lv_obj_t *ui_Label_X_Position2;
extern lv_obj_t *ui_Label_X_Position_Number2;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_DP4;
extern lv_obj_t *ui_Label_Y_Position2;
extern lv_obj_t *ui_Label_Time_7;
extern lv_obj_t *ui_BTN_Menu_Print_S8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

