// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 3d_printer

#include "../ui.h"

lv_obj_t *ui_Screen_2_Move1 = NULL;lv_obj_t *ui_Background4 = NULL;lv_obj_t *ui_Panel_Header4 = NULL;lv_obj_t *ui_Label_Header5 = NULL;lv_obj_t *ui_Label_Header7 = NULL;lv_obj_t *ui_BTN_Menu_Print_S5 = NULL;lv_obj_t *ui_S1_Content_Panel4 = NULL;lv_obj_t *ui_Display_Pos_y1 = NULL;lv_obj_t *ui_DP6 = NULL;lv_obj_t *ui_Label_Z_Position1 = NULL;lv_obj_t *ui_Label_Z_Position_Number1 = NULL;lv_obj_t *ui_BTN_Move_Z1 = NULL;lv_obj_t *ui_GLOW_7 = NULL;lv_obj_t *ui_GLOW_8 = NULL;lv_obj_t *ui_BTN_Image_Top1 = NULL;lv_obj_t *ui_Label_Z_Position_1 = NULL;lv_obj_t *ui_Arrow_Z_up1 = NULL;lv_obj_t *ui_Arrow_Z_Down1 = NULL;lv_obj_t *ui_BTN_Reset1 = NULL;lv_obj_t *ui_Label_Reset3 = NULL;lv_obj_t *ui_Roller_Number3 = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Roller7 = NULL;lv_obj_t *ui_Label_Steps3 = NULL;lv_obj_t *ui_BTN_Move_Z2 = NULL;lv_obj_t *ui_GLOW_9 = NULL;lv_obj_t *ui_GLOW_10 = NULL;lv_obj_t *ui_BTN_Image_Top2 = NULL;lv_obj_t *ui_Label_Z_Position_3 = NULL;lv_obj_t *ui_Arrow_Z_up2 = NULL;lv_obj_t *ui_Arrow_Z_Down2 = NULL;lv_obj_t *ui_BTN_Move_Z3 = NULL;lv_obj_t *ui_GLOW_11 = NULL;lv_obj_t *ui_GLOW_12 = NULL;lv_obj_t *ui_BTN_Image_Top3 = NULL;lv_obj_t *ui_Label_Z_Position_4 = NULL;lv_obj_t *ui_Arrow_Z_up3 = NULL;lv_obj_t *ui_Arrow_Z_Down3 = NULL;lv_obj_t *ui_Display_Pos_XY2 = NULL;lv_obj_t *ui_DP7 = NULL;lv_obj_t *ui_Label_X_Position2 = NULL;lv_obj_t *ui_Label_X_Position_Number2 = NULL;lv_obj_t *ui_Panel7 = NULL;lv_obj_t *ui_DP4 = NULL;lv_obj_t *ui_Label_Y_Position2 = NULL;lv_obj_t *ui_Label_Time_7 = NULL;lv_obj_t *ui_BTN_Menu_Print_S8 = NULL;
// event funtions
void ui_event_BTN_Menu_Print_S5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      // 处理主页按钮点击事件
      extern void npwt_ui_handle_home_button_clicked(void);
      npwt_ui_handle_home_button_clicked();
      _ui_screen_change( &ui_Screen_1_Print1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen_1_Print1_screen_init);
}
}

void ui_event_GLOW_7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_GLOW_7, 0);
      _ui_state_modify( ui_Arrow_Z_up1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_GLOW_7, 0);
      _ui_state_modify( ui_Arrow_Z_up1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      // 压力增加 (减少负压的绝对值)
      extern void npwt_ui_handle_pressure_adjust(int16_t delta);
      npwt_ui_handle_pressure_adjust(10);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_GLOW_7, 0);
      _ui_state_modify( ui_Arrow_Z_up1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_GLOW_8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_GLOW_8, 0);
      _ui_state_modify( ui_Arrow_Z_Down1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_GLOW_8, 0);
      _ui_state_modify( ui_Arrow_Z_Down1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      // 压力减少 (增加负压的绝对值)
      extern void npwt_ui_handle_pressure_adjust(int16_t delta);
      npwt_ui_handle_pressure_adjust(-10);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_GLOW_8, 0);
      _ui_state_modify( ui_Arrow_Z_Down1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_GLOW_9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_GLOW_9, 0);
      _ui_state_modify( ui_Arrow_Z_up2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_GLOW_9, 0);
      _ui_state_modify( ui_Arrow_Z_up2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      // 工作时间增加
      extern void npwt_ui_handle_work_time_adjust(int8_t delta);
      npwt_ui_handle_work_time_adjust(1);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_GLOW_9, 0);
      _ui_state_modify( ui_Arrow_Z_up2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_GLOW_10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_GLOW_10, 0);
      _ui_state_modify( ui_Arrow_Z_Down2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_GLOW_10, 0);
      _ui_state_modify( ui_Arrow_Z_Down2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      // 工作时间减少
      extern void npwt_ui_handle_work_time_adjust(int8_t delta);
      npwt_ui_handle_work_time_adjust(-1);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_GLOW_10, 0);
      _ui_state_modify( ui_Arrow_Z_Down2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_GLOW_11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_GLOW_11, 0);
      _ui_state_modify( ui_Arrow_Z_up3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_GLOW_11, 0);
      _ui_state_modify( ui_Arrow_Z_up3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      // 休息时间增加
      extern void npwt_ui_handle_rest_time_adjust(int8_t delta);
      npwt_ui_handle_rest_time_adjust(1);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_GLOW_11, 0);
      _ui_state_modify( ui_Arrow_Z_up3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_GLOW_12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_GLOW_12, 0);
      _ui_state_modify( ui_Arrow_Z_Down3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_GLOW_12, 0);
      _ui_state_modify( ui_Arrow_Z_Down3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      // 休息时间减少
      extern void npwt_ui_handle_rest_time_adjust(int8_t delta);
      npwt_ui_handle_rest_time_adjust(-1);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_GLOW_12, 0);
      _ui_state_modify( ui_Arrow_Z_Down3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

// 模式滚轮事件处理
void ui_event_Roller_Mode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      // 模式滚轮值变化
      lv_obj_t * roller = lv_event_get_target(e);
      uint16_t selected = lv_roller_get_selected(roller);
      
      // 调用UI处理函数来设置模式
      extern void npwt_ui_handle_mode_switch(void);
      // 这里简单地调用模式切换函数，让它在业务逻辑中处理
      npwt_ui_handle_mode_switch();
}
}

// 保存按钮事件处理
void ui_event_BTN_Save( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      extern void npwt_ui_handle_save_settings(void);
      npwt_ui_handle_save_settings();
}
}

// build funtions

void ui_Screen_2_Move1_screen_init(void)
{
ui_Screen_2_Move1 = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_Screen_2_Move1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_2_Move1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Background4 = lv_img_create(ui_Screen_2_Move1);
lv_img_set_src(ui_Background4, &ui_img_new_bg_png);
lv_obj_set_width( ui_Background4, 800);
lv_obj_set_height( ui_Background4, 480);
lv_obj_set_align( ui_Background4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Background4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_Panel_Header4 = lv_obj_create(ui_Background4);
lv_obj_set_width( ui_Panel_Header4, 665);
lv_obj_set_height( ui_Panel_Header4, 39);
lv_obj_set_x( ui_Panel_Header4, -30 );
lv_obj_set_y( ui_Panel_Header4, 0 );
lv_obj_set_align( ui_Panel_Header4, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Panel_Header4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_Header4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_Header4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Panel_Header4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Panel_Header4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_Header4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Header5 = lv_label_create(ui_Panel_Header4);
lv_obj_set_width( ui_Label_Header5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Header5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Header5, -78 );
lv_obj_set_y( ui_Label_Header5, -3 );
lv_obj_set_align( ui_Label_Header5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Header5,"THU-NPWT");
lv_label_set_recolor(ui_Label_Header5,"true");
lv_obj_set_style_text_color(ui_Label_Header5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Header5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Header5, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Header7 = lv_label_create(ui_Panel_Header4);
lv_obj_set_width( ui_Label_Header7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Header7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Header7, 58 );
lv_obj_set_y( ui_Label_Header7, -3 );
lv_obj_set_align( ui_Label_Header7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Header7,"负压伤口治疗装置");
lv_label_set_recolor(ui_Label_Header7,"true");
lv_obj_set_style_text_color(ui_Label_Header7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Header7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Header7, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Menu_Print_S5 = lv_img_create(ui_Screen_2_Move1);
lv_img_set_src(ui_BTN_Menu_Print_S5, &ui_img_btn_print_png);
lv_obj_set_width( ui_BTN_Menu_Print_S5, 79);
lv_obj_set_height( ui_BTN_Menu_Print_S5, 240);
lv_obj_add_flag( ui_BTN_Menu_Print_S5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Print_S5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BTN_Menu_Print_S5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_S1_Content_Panel4 = lv_obj_create(ui_Screen_2_Move1);
lv_obj_set_width( ui_S1_Content_Panel4, 720);
lv_obj_set_height( ui_S1_Content_Panel4, 417);
lv_obj_set_x( ui_S1_Content_Panel4, -4 );
lv_obj_set_y( ui_S1_Content_Panel4, -14 );
lv_obj_set_align( ui_S1_Content_Panel4, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_S1_Content_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_S1_Content_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_S1_Content_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_S1_Content_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_S1_Content_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_S1_Content_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_S1_Content_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_S1_Content_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_S1_Content_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_S1_Content_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Display_Pos_y1 = lv_obj_create(ui_S1_Content_Panel4);
lv_obj_set_width( ui_Display_Pos_y1, 161);
lv_obj_set_height( ui_Display_Pos_y1, 79);
lv_obj_set_x( ui_Display_Pos_y1, 28 );
lv_obj_set_y( ui_Display_Pos_y1, 15 );
lv_obj_clear_flag( ui_Display_Pos_y1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Display_Pos_y1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Display_Pos_y1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Display_Pos_y1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Display_Pos_y1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Display_Pos_y1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Display_Pos_y1, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Display_Pos_y1, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Display_Pos_y1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Display_Pos_y1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Display_Pos_y1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Display_Pos_y1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Display_Pos_y1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Display_Pos_y1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DP6 = lv_obj_create(ui_Display_Pos_y1);
lv_obj_set_width( ui_DP6, lv_pct(97));
lv_obj_set_height( ui_DP6, lv_pct(100));
lv_obj_set_align( ui_DP6, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_DP6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DP6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DP6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_DP6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_DP6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DP6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DP6, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DP6, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DP6, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DP6, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Z_Position1 = lv_label_create(ui_DP6);
lv_obj_set_width( ui_Label_Z_Position1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Z_Position1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Z_Position1, -4 );
lv_obj_set_y( ui_Label_Z_Position1, -2 );
lv_obj_set_align( ui_Label_Z_Position1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Z_Position1,"设定负压");
lv_label_set_recolor(ui_Label_Z_Position1,"true");
lv_obj_set_style_text_color(ui_Label_Z_Position1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Z_Position1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Z_Position1, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Z_Position_Number1 = lv_label_create(ui_DP6);
lv_obj_set_width( ui_Label_Z_Position_Number1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Z_Position_Number1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Z_Position_Number1, -2 );
lv_obj_set_y( ui_Label_Z_Position_Number1, 11 );
lv_obj_set_align( ui_Label_Z_Position_Number1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Z_Position_Number1,"-120mmHg");
lv_obj_set_style_text_color(ui_Label_Z_Position_Number1, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Z_Position_Number1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Z_Position_Number1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Move_Z1 = lv_img_create(ui_S1_Content_Panel4);
lv_img_set_src(ui_BTN_Move_Z1, &ui_img_btn_z_botton_png);
lv_obj_set_width( ui_BTN_Move_Z1, 140);
lv_obj_set_height( ui_BTN_Move_Z1, 312);
lv_obj_set_x( ui_BTN_Move_Z1, -256 );
lv_obj_set_y( ui_BTN_Move_Z1, 43 );
lv_obj_set_align( ui_BTN_Move_Z1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Move_Z1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_GLOW_7 = lv_obj_create(ui_BTN_Move_Z1);
lv_obj_set_width( ui_GLOW_7, 75);
lv_obj_set_height( ui_GLOW_7, 70);
lv_obj_set_x( ui_GLOW_7, 0 );
lv_obj_set_y( ui_GLOW_7, 34 );
lv_obj_set_align( ui_GLOW_7, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_GLOW_7, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GLOW_7, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GLOW_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_GLOW_7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_GLOW_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GLOW_7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_GLOW_7, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_GLOW_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_GLOW_7, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_GLOW_7, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_GLOW_7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GLOW_8 = lv_obj_create(ui_BTN_Move_Z1);
lv_obj_set_width( ui_GLOW_8, 75);
lv_obj_set_height( ui_GLOW_8, 70);
lv_obj_set_x( ui_GLOW_8, 0 );
lv_obj_set_y( ui_GLOW_8, 211 );
lv_obj_set_align( ui_GLOW_8, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_GLOW_8, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GLOW_8, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GLOW_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_GLOW_8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_GLOW_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GLOW_8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_GLOW_8, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_GLOW_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_GLOW_8, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_GLOW_8, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_GLOW_8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Image_Top1 = lv_img_create(ui_BTN_Move_Z1);
lv_img_set_src(ui_BTN_Image_Top1, &ui_img_btn_z_top_png);
lv_obj_set_width( ui_BTN_Image_Top1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Image_Top1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Image_Top1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Image_Top1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_Label_Z_Position_1 = lv_label_create(ui_BTN_Image_Top1);
lv_obj_set_width( ui_Label_Z_Position_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Z_Position_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Z_Position_1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Z_Position_1,"+\n设定\n负压\n-");
lv_label_set_recolor(ui_Label_Z_Position_1,"true");
lv_obj_set_style_text_color(ui_Label_Z_Position_1, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Z_Position_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_Z_Position_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_Z_Position_1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Z_Position_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Z_Position_1, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arrow_Z_up1 = lv_img_create(ui_BTN_Image_Top1);
lv_img_set_src(ui_Arrow_Z_up1, &ui_img_arrow_up_png);
lv_obj_set_width( ui_Arrow_Z_up1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Z_up1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Z_up1, 0 );
lv_obj_set_y( ui_Arrow_Z_up1, 20 );
lv_obj_set_align( ui_Arrow_Z_up1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Arrow_Z_up1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Z_up1, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Z_up1, lv_color_hex(0x00D1FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor(ui_Arrow_Z_up1, lv_color_hex(0x00D1FF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Arrow_Z_Down1 = lv_img_create(ui_BTN_Image_Top1);
lv_img_set_src(ui_Arrow_Z_Down1, &ui_img_arrow_down_png);
lv_obj_set_width( ui_Arrow_Z_Down1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Z_Down1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Z_Down1, 0 );
lv_obj_set_y( ui_Arrow_Z_Down1, -20 );
lv_obj_set_align( ui_Arrow_Z_Down1, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Arrow_Z_Down1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Z_Down1, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_Down1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Z_Down1, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_Down1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_BTN_Reset1 = lv_imgbtn_create(ui_S1_Content_Panel4);
lv_imgbtn_set_src(ui_BTN_Reset1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_btn_main_off_png, NULL);
lv_imgbtn_set_src(ui_BTN_Reset1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
lv_imgbtn_set_src(ui_BTN_Reset1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_btn_main_on_png, NULL);
lv_imgbtn_set_src(ui_BTN_Reset1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_btn_main_on_png, NULL);
lv_obj_set_height( ui_BTN_Reset1, 66);
lv_obj_set_width( ui_BTN_Reset1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_x( ui_BTN_Reset1, -22 );
lv_obj_set_y( ui_BTN_Reset1, 281 );
lv_obj_set_align( ui_BTN_Reset1, LV_ALIGN_TOP_RIGHT );
lv_obj_set_style_text_color(ui_BTN_Reset1, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BTN_Reset1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BTN_Reset1, lv_color_hex(0x00B9FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_BTN_Reset1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_BTN_Reset1, lv_color_hex(0x06CEFB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_BTN_Reset1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label_Reset3 = lv_label_create(ui_BTN_Reset1);
lv_obj_set_width( ui_Label_Reset3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Reset3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Reset3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Reset3,"保存");
lv_label_set_recolor(ui_Label_Reset3,"true");
lv_obj_set_style_text_align(ui_Label_Reset3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Reset3, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller_Number3 = lv_obj_create(ui_S1_Content_Panel4);
lv_obj_set_height( ui_Roller_Number3, 215);
lv_obj_set_width( ui_Roller_Number3, LV_SIZE_CONTENT);  /// 165
lv_obj_set_x( ui_Roller_Number3, 254 );
lv_obj_set_y( ui_Roller_Number3, -79 );
lv_obj_set_align( ui_Roller_Number3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Roller_Number3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Roller_Number3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Number3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Roller_Number3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Roller_Number3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Roller_Number3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Roller_Number3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Roller_Number3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Roller_Number3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Roller_Number3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_img_create(ui_Roller_Number3);
lv_img_set_src(ui_Image6, &ui_img_roller_bg_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_Roller7 = lv_roller_create(ui_Roller_Number3);
lv_roller_set_options( ui_Roller7, "持续模式\n间歇模式\n动态模式", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller7, 142);
lv_obj_set_height( ui_Roller7, 131);
lv_obj_set_align( ui_Roller7, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_Roller7, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller7, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Roller7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Roller7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Roller7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller7, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller7, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller7, &ui_font_chinese18, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller7, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller7, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label_Steps3 = lv_label_create(ui_Roller_Number3);
lv_obj_set_width( ui_Label_Steps3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Steps3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Steps3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Steps3,"负压治疗模式");
lv_label_set_recolor(ui_Label_Steps3,"true");
lv_obj_set_style_text_color(ui_Label_Steps3, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Steps3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Steps3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Steps3, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Move_Z2 = lv_img_create(ui_S1_Content_Panel4);
lv_img_set_src(ui_BTN_Move_Z2, &ui_img_btn_z_botton_png);
lv_obj_set_width( ui_BTN_Move_Z2, 140);
lv_obj_set_height( ui_BTN_Move_Z2, 312);
lv_obj_set_x( ui_BTN_Move_Z2, -83 );
lv_obj_set_y( ui_BTN_Move_Z2, 45 );
lv_obj_set_align( ui_BTN_Move_Z2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Move_Z2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_GLOW_9 = lv_obj_create(ui_BTN_Move_Z2);
lv_obj_set_width( ui_GLOW_9, 75);
lv_obj_set_height( ui_GLOW_9, 70);
lv_obj_set_x( ui_GLOW_9, 0 );
lv_obj_set_y( ui_GLOW_9, 34 );
lv_obj_set_align( ui_GLOW_9, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_GLOW_9, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GLOW_9, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GLOW_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_GLOW_9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_GLOW_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GLOW_9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_GLOW_9, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_GLOW_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_GLOW_9, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_GLOW_9, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_GLOW_9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GLOW_10 = lv_obj_create(ui_BTN_Move_Z2);
lv_obj_set_width( ui_GLOW_10, 75);
lv_obj_set_height( ui_GLOW_10, 70);
lv_obj_set_x( ui_GLOW_10, 0 );
lv_obj_set_y( ui_GLOW_10, 211 );
lv_obj_set_align( ui_GLOW_10, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_GLOW_10, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GLOW_10, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GLOW_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_GLOW_10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_GLOW_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GLOW_10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_GLOW_10, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_GLOW_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_GLOW_10, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_GLOW_10, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_GLOW_10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Image_Top2 = lv_img_create(ui_BTN_Move_Z2);
lv_img_set_src(ui_BTN_Image_Top2, &ui_img_btn_z_top_png);
lv_obj_set_width( ui_BTN_Image_Top2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Image_Top2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Image_Top2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Image_Top2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_Label_Z_Position_3 = lv_label_create(ui_BTN_Image_Top2);
lv_obj_set_width( ui_Label_Z_Position_3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Z_Position_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Z_Position_3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Z_Position_3,"+\n工作\n时长\n-");
lv_label_set_recolor(ui_Label_Z_Position_3,"true");
lv_obj_set_style_text_color(ui_Label_Z_Position_3, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Z_Position_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_Z_Position_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_Z_Position_3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Z_Position_3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Z_Position_3, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arrow_Z_up2 = lv_img_create(ui_BTN_Image_Top2);
lv_img_set_src(ui_Arrow_Z_up2, &ui_img_arrow_up_png);
lv_obj_set_width( ui_Arrow_Z_up2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Z_up2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Z_up2, 0 );
lv_obj_set_y( ui_Arrow_Z_up2, 20 );
lv_obj_set_align( ui_Arrow_Z_up2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Arrow_Z_up2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Z_up2, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Z_up2, lv_color_hex(0x00D1FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up2, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor(ui_Arrow_Z_up2, lv_color_hex(0x00D1FF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Arrow_Z_Down2 = lv_img_create(ui_BTN_Image_Top2);
lv_img_set_src(ui_Arrow_Z_Down2, &ui_img_arrow_down_png);
lv_obj_set_width( ui_Arrow_Z_Down2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Z_Down2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Z_Down2, 0 );
lv_obj_set_y( ui_Arrow_Z_Down2, -20 );
lv_obj_set_align( ui_Arrow_Z_Down2, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Arrow_Z_Down2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Z_Down2, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_Down2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Z_Down2, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_Down2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_BTN_Move_Z3 = lv_img_create(ui_S1_Content_Panel4);
lv_img_set_src(ui_BTN_Move_Z3, &ui_img_btn_z_botton_png);
lv_obj_set_width( ui_BTN_Move_Z3, 140);
lv_obj_set_height( ui_BTN_Move_Z3, 312);
lv_obj_set_x( ui_BTN_Move_Z3, 68 );
lv_obj_set_y( ui_BTN_Move_Z3, 43 );
lv_obj_set_align( ui_BTN_Move_Z3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Move_Z3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_GLOW_11 = lv_obj_create(ui_BTN_Move_Z3);
lv_obj_set_width( ui_GLOW_11, 75);
lv_obj_set_height( ui_GLOW_11, 70);
lv_obj_set_x( ui_GLOW_11, 0 );
lv_obj_set_y( ui_GLOW_11, 34 );
lv_obj_set_align( ui_GLOW_11, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_GLOW_11, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GLOW_11, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GLOW_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_GLOW_11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_GLOW_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GLOW_11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_GLOW_11, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_GLOW_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_GLOW_11, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_GLOW_11, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_GLOW_11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GLOW_12 = lv_obj_create(ui_BTN_Move_Z3);
lv_obj_set_width( ui_GLOW_12, 75);
lv_obj_set_height( ui_GLOW_12, 70);
lv_obj_set_x( ui_GLOW_12, 0 );
lv_obj_set_y( ui_GLOW_12, 211 );
lv_obj_set_align( ui_GLOW_12, LV_ALIGN_TOP_MID );
lv_obj_set_style_radius(ui_GLOW_12, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GLOW_12, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GLOW_12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_GLOW_12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_GLOW_12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GLOW_12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_GLOW_12, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_GLOW_12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_GLOW_12, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_GLOW_12, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_GLOW_12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Image_Top3 = lv_img_create(ui_BTN_Move_Z3);
lv_img_set_src(ui_BTN_Image_Top3, &ui_img_btn_z_top_png);
lv_obj_set_width( ui_BTN_Image_Top3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Image_Top3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Image_Top3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Image_Top3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags

ui_Label_Z_Position_4 = lv_label_create(ui_BTN_Image_Top3);
lv_obj_set_width( ui_Label_Z_Position_4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Z_Position_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Z_Position_4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Z_Position_4,"+\n休息\n时长\n-");
lv_label_set_recolor(ui_Label_Z_Position_4,"true");
lv_obj_set_style_text_color(ui_Label_Z_Position_4, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Z_Position_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_Z_Position_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_Z_Position_4, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Z_Position_4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Z_Position_4, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arrow_Z_up3 = lv_img_create(ui_BTN_Image_Top3);
lv_img_set_src(ui_Arrow_Z_up3, &ui_img_arrow_up_png);
lv_obj_set_width( ui_Arrow_Z_up3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Z_up3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Z_up3, 0 );
lv_obj_set_y( ui_Arrow_Z_up3, 20 );
lv_obj_set_align( ui_Arrow_Z_up3, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Arrow_Z_up3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Z_up3, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Z_up3, lv_color_hex(0x00D1FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up3, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor(ui_Arrow_Z_up3, lv_color_hex(0x00D1FF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_up3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Arrow_Z_Down3 = lv_img_create(ui_BTN_Image_Top3);
lv_img_set_src(ui_Arrow_Z_Down3, &ui_img_arrow_down_png);
lv_obj_set_width( ui_Arrow_Z_Down3, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Arrow_Z_Down3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Arrow_Z_Down3, 0 );
lv_obj_set_y( ui_Arrow_Z_Down3, -20 );
lv_obj_set_align( ui_Arrow_Z_Down3, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Arrow_Z_Down3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_set_style_img_recolor(ui_Arrow_Z_Down3, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_Down3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_Z_Down3, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_Z_Down3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Display_Pos_XY2 = lv_obj_create(ui_Screen_2_Move1);
lv_obj_set_width( ui_Display_Pos_XY2, 283);
lv_obj_set_height( ui_Display_Pos_XY2, 79);
lv_obj_set_x( ui_Display_Pos_XY2, 287 );
lv_obj_set_y( ui_Display_Pos_XY2, 66 );
lv_obj_clear_flag( ui_Display_Pos_XY2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Display_Pos_XY2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Display_Pos_XY2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Display_Pos_XY2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Display_Pos_XY2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Display_Pos_XY2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Display_Pos_XY2, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Display_Pos_XY2, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Display_Pos_XY2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Display_Pos_XY2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Display_Pos_XY2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Display_Pos_XY2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Display_Pos_XY2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Display_Pos_XY2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DP7 = lv_obj_create(ui_Display_Pos_XY2);
lv_obj_set_width( ui_DP7, lv_pct(50));
lv_obj_set_height( ui_DP7, lv_pct(100));
lv_obj_set_align( ui_DP7, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_DP7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DP7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DP7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_DP7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_DP7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DP7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DP7, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DP7, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DP7, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DP7, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_X_Position2 = lv_label_create(ui_DP7);
lv_obj_set_width( ui_Label_X_Position2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_X_Position2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_X_Position2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_X_Position2,"工作周期时长");
lv_label_set_recolor(ui_Label_X_Position2,"true");
lv_obj_set_style_text_color(ui_Label_X_Position2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_X_Position2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_X_Position2, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_X_Position_Number2 = lv_label_create(ui_DP7);
lv_obj_set_width( ui_Label_X_Position_Number2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_X_Position_Number2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_X_Position_Number2, 0 );
lv_obj_set_y( ui_Label_X_Position_Number2, 10 );
lv_obj_set_align( ui_Label_X_Position_Number2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_X_Position_Number2,"5min");
lv_obj_set_style_text_color(ui_Label_X_Position_Number2, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_X_Position_Number2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_X_Position_Number2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_Display_Pos_XY2);
lv_obj_set_width( ui_Panel7, 2);
lv_obj_set_height( ui_Panel7, 50);
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DP4 = lv_obj_create(ui_Display_Pos_XY2);
lv_obj_set_width( ui_DP4, lv_pct(50));
lv_obj_set_height( ui_DP4, lv_pct(100));
lv_obj_set_align( ui_DP4, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_DP4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DP4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DP4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_DP4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_DP4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DP4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DP4, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DP4, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DP4, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DP4, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Y_Position2 = lv_label_create(ui_DP4);
lv_obj_set_width( ui_Label_Y_Position2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Y_Position2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Y_Position2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Y_Position2,"休息周期时长");
lv_label_set_recolor(ui_Label_Y_Position2,"true");
lv_obj_set_style_text_color(ui_Label_Y_Position2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Y_Position2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Y_Position2, &ui_font_chinese18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Time_7 = lv_label_create(ui_DP4);
lv_obj_set_width( ui_Label_Time_7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Time_7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Time_7, 0 );
lv_obj_set_y( ui_Label_Time_7, 10 );
lv_obj_set_align( ui_Label_Time_7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Time_7,"3min");
lv_obj_set_style_text_color(ui_Label_Time_7, lv_color_hex(0xDBE6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Time_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Time_7, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Menu_Print_S8 = lv_img_create(ui_Screen_2_Move1);
lv_img_set_src(ui_BTN_Menu_Print_S8, &ui_img_new_setting_png);
lv_obj_set_width( ui_BTN_Menu_Print_S8, 79);
lv_obj_set_height( ui_BTN_Menu_Print_S8, 240);
lv_obj_set_x( ui_BTN_Menu_Print_S8, 0 );
lv_obj_set_y( ui_BTN_Menu_Print_S8, 240 );
lv_obj_add_flag( ui_BTN_Menu_Print_S8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Print_S8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_BTN_Menu_Print_S5, ui_event_BTN_Menu_Print_S5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GLOW_7, ui_event_GLOW_7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GLOW_8, ui_event_GLOW_8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GLOW_9, ui_event_GLOW_9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GLOW_10, ui_event_GLOW_10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GLOW_11, ui_event_GLOW_11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GLOW_12, ui_event_GLOW_12, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Roller7, ui_event_Roller_Mode, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Reset1, ui_event_BTN_Save, LV_EVENT_ALL, NULL);

}

void ui_Screen_2_Move1_screen_destroy(void)
{
   if (ui_Screen_2_Move1) lv_obj_del(ui_Screen_2_Move1);

// NULL screen variables
ui_Screen_2_Move1= NULL;
ui_Background4= NULL;
ui_Panel_Header4= NULL;
ui_Label_Header5= NULL;
ui_Label_Header7= NULL;
ui_BTN_Menu_Print_S5= NULL;
ui_S1_Content_Panel4= NULL;
ui_Display_Pos_y1= NULL;
ui_DP6= NULL;
ui_Label_Z_Position1= NULL;
ui_Label_Z_Position_Number1= NULL;
ui_BTN_Move_Z1= NULL;
ui_GLOW_7= NULL;
ui_GLOW_8= NULL;
ui_BTN_Image_Top1= NULL;
ui_Label_Z_Position_1= NULL;
ui_Arrow_Z_up1= NULL;
ui_Arrow_Z_Down1= NULL;
ui_BTN_Reset1= NULL;
ui_Label_Reset3= NULL;
ui_Roller_Number3= NULL;
ui_Image6= NULL;
ui_Roller7= NULL;
ui_Label_Steps3= NULL;
ui_BTN_Move_Z2= NULL;
ui_GLOW_9= NULL;
ui_GLOW_10= NULL;
ui_BTN_Image_Top2= NULL;
ui_Label_Z_Position_3= NULL;
ui_Arrow_Z_up2= NULL;
ui_Arrow_Z_Down2= NULL;
ui_BTN_Move_Z3= NULL;
ui_GLOW_11= NULL;
ui_GLOW_12= NULL;
ui_BTN_Image_Top3= NULL;
ui_Label_Z_Position_4= NULL;
ui_Arrow_Z_up3= NULL;
ui_Arrow_Z_Down3= NULL;
ui_Display_Pos_XY2= NULL;
ui_DP7= NULL;
ui_Label_X_Position2= NULL;
ui_Label_X_Position_Number2= NULL;
ui_Panel7= NULL;
ui_DP4= NULL;
ui_Label_Y_Position2= NULL;
ui_Label_Time_7= NULL;
ui_BTN_Menu_Print_S8= NULL;

}
