// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 3d_printer

#ifndef UI_SCREEN_1_PRINT1_H
#define UI_SCREEN_1_PRINT1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_1_Print1
extern void ui_Screen_1_Print1_screen_init(void);
extern void ui_Screen_1_Print1_screen_destroy(void);
extern lv_obj_t *ui_Screen_1_Print1;
extern lv_obj_t *ui_Background3;
extern lv_obj_t *ui_Panel_Header3;
extern lv_obj_t *ui_Label_Header3;
extern lv_obj_t *ui_Label_Header6;
extern lv_obj_t *ui_BTN_Menu_Print_S4;
extern void ui_event_BTN_Menu_Setting_S4( lv_event_t * e);
extern lv_obj_t *ui_BTN_Menu_Setting_S4;
extern lv_obj_t *ui_S1_Content_Panel3;
extern lv_obj_t *ui_Display_Heat_S2;
extern lv_obj_t *ui_DT6;
extern lv_obj_t *ui_Label_Printing_Head_Temp1;
extern lv_obj_t *ui_IMG_Head2;
extern lv_obj_t *ui_Label_Head_Temp2;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_DT3_copy1;
extern lv_obj_t *ui_Label_Printing_Bed_Temp2;
extern lv_obj_t *ui_IMG_Head3;
extern lv_obj_t *ui_Label_Bed_Temp2;
extern lv_obj_t *ui_Label_Printing_Bed_Temp3;
extern lv_obj_t *ui_Label_Printing_Head_Temp3;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Panel_Buttons_S2;
extern lv_obj_t *ui_BTN_Pause1;
extern lv_obj_t *ui_BTN_Pause_Top1;
extern lv_obj_t *ui_Image_Pause1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

