// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: 3d_printer

#ifndef _3D_PRINTER_UI_H
#define _3D_PRINTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen_1_Print1.h"
#include "screens/ui_Screen_2_Move1.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * OpaOn_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * OpaOff_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * ScreenIn_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * MenuIn_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * MenuOut_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * ScreenOut_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_new_bg_png);   // assets/new_bg.png
LV_IMG_DECLARE( ui_img_new_home_png);   // assets/new_home.png
LV_IMG_DECLARE( ui_img_btn_setting_png);   // assets/btn_setting.png
LV_IMG_DECLARE( ui_img_icn_head_png);   // assets/icn_head.png
LV_IMG_DECLARE( ui_img_icn_bed_png);   // assets/icn_bed.png
LV_IMG_DECLARE( ui_img_btn_print_down_png);   // assets/btn_print_down.png
LV_IMG_DECLARE( ui_img_btn_print_top_off_png);   // assets/btn_print_top_off.png
LV_IMG_DECLARE( ui_img_open_png);   // assets/open.png
LV_IMG_DECLARE( ui_img_btn_print_png);   // assets/btn_print.png
LV_IMG_DECLARE( ui_img_btn_z_botton_png);   // assets/btn_z_botton.png
LV_IMG_DECLARE( ui_img_btn_z_top_png);   // assets/btn_z_top.png
LV_IMG_DECLARE( ui_img_arrow_up_png);   // assets/arrow_up.png
LV_IMG_DECLARE( ui_img_arrow_down_png);   // assets/arrow_down.png
LV_IMG_DECLARE( ui_img_btn_main_off_png);   // assets/btn_main_off.png
LV_IMG_DECLARE( ui_img_btn_main_on_png);   // assets/btn_main_on.png
LV_IMG_DECLARE( ui_img_roller_bg_png);   // assets/roller_bg.png
LV_IMG_DECLARE( ui_img_new_setting_png);   // assets/new_setting.png

// FONTS
LV_FONT_DECLARE( ui_font_Small_Font);
LV_FONT_DECLARE( ui_font_chinese18);
LV_FONT_DECLARE( ui_font_chinese24);
LV_FONT_DECLARE( ui_font_notosans24);
LV_FONT_DECLARE( ui_font_notosans56);
LV_FONT_DECLARE( ui_font_notosans150);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
